#' Import bursary, abstract and registration data from Google Sheets
#' 
#' @description 
#' @param data Type of data imported - specifies the field to look within 
#' for the URL: c('bursary', 'abstracts', 'registration')
#' @examples 
#' data <- import_data(data = 'abstracts')
#' abstract_data <- data$abstract_data
import_data <- function(data = 'abstracts'){
  
  # Specify access rights not needed for read only access to GSheets
  googlesheets4::gs4_deauth()
  
  # Set blank output list
  output <- list()
  
  # Lookup URL to find based on data type - data sourced from inputs.csv 
  # in output folder, generated by set_values()
  dat <- read.csv(here::here("outputs", "inputs.csv"))
  if(any(grepl(data, 'bursary')) == TRUE){
    bursary_url <- maditr::vlookup('absSubmissions', dat, lookup_column = 'label')
    # Read in data
    bursary_data <- list(bursary_data = googlesheets4::read_sheet(bursary_url))
    output <- append(output, bursary_data)
  }
  if(any(grepl(data, 'abstracts')) == TRUE){
    abstract_url <- maditr::vlookup('absSubmissions', dat, lookup_column = 'label')
    # Read in data
    abstract_data <- list(abstract_data = googlesheets4::read_sheet(abstract_url))
    output <- append(output, abstract_data)
  }
  if(any(grepl(data, 'registration')) == TRUE){
    registration_url <- maditr::vlookup('registrations', dat, lookup_column = 'label')
    # Read in data
    registration_data <- list(registration_data = googlesheets4::read_sheet(registration_url))
    output <- append(output, registration_data)
  }
  
  return(output)
  
}
