#' Publish recording and metadata to a single record on Zenodo
#' 
#' @description 
#' @param presenter_data
#' @examples 
#' data <- import_data(data = 'abstracts')
#' abstract_data <- data$abstract_data
#' presenter_data <- abstract_data[28,]
send2zenodo <- function(presenter_data){
  
  #### Read in metadata #### 
  # Lookup ESMARConf name - data sourced from inputs.csv in output folder, generated by set_values()
  dat <- read.csv(here::here("outputs", "inputs.csv"))
  ESMARConfName <- maditr::vlookup('ESMARConfName', dat, lookup_column = 'label')
  ESMARConf_startDate <- maditr::vlookup('ESMARConf_startDate', dat, lookup_column = 'label')
  ESMARConf_endDate <- maditr::vlookup('ESMARConf_endDate', dat, lookup_column = 'label')
  #### end metadata section ####
  
  #### Tidy presenter_data ####
  # Replace NA with '' across presenter_data
  presenter_data[] <- lapply(presenter_data, as.character)
  presenter_data[is.na(presenter_data)] <- ''
  #### end tidy presenter data section ####
  
  #### Send to Zenodo ####
  # Connect to Zenodo REST API
  zenodo <- zen4R::ZenodoManager$new(
    token = 'EZINvEsMsQp6wepm3HsDA1HZAN1d74Ykll8maLV22Fj2XPauG5ad15hIy0tj', 
    logger = "INFO" # use "DEBUG" to see detailed API operation logs, use NULL if you don't want logs at all
  )
  
  # Create record
  # Generate local empty record not yet deposited on Zenodo
  # Get detailed help here: ?ZenodoRecord
  myrec <- zenodo$createEmptyRecord()
  myrec$setPublicationDate(as.Date(Sys.Date()))
  myrec$setAccessRight("embargoed")
  myrec$setEmbargoDate(as.Date(presenter_data$time_start)) #- not currently working - throws the following error: 'Error in .class1(object) : object 'publicationDate' not found'
  myrec$setTitle(presenter_data$title)
  myrec$setDescription(presenter_data$abstract)
  myrec$setUploadType("presentation")
  myrec$addCreator(name = presenter_data$name, affiliation = presenter_data$affiliation, orcid = presenter_data$ORCID)
  myrec$setLanguage('eng')
  myrec$setKeywords(c(ESMARConfName,'evidence synthesis','meta-analysis','RStats'))
  myrec$setCommunities(tolower(ESMARConfName))
  myrec$setConferenceTitle(paste0('Evidence Synthesis and Meta-Analysis in R Conference ', substr(ESMARConfName, 10,13)))
  myrec$setConferenceAcronym(ESMARConfName)
  myrec$setConferenceDates(paste0(format(as.Date(ESMARConf_startDate), "%d"), ' to ', format(as.Date(ESMARConf_endDate), "%d %B %Y")))
  myrec$setConferencePlace('online')
  myrec$setConferenceUrl('https://esmarconf.github.io/')
  myrec$setConferenceSession(presenter_data$session)
  # Deposit on zenodo
  myrec <- zenodo$depositRecord(myrec)
  # Get record id
  myrec$id
  # Upload file - get detailed help here: ??Zenodo
  zenodo$uploadFile(file.choose(), myrec)
  # Find out doi from Zenodo
  doi <- myrec$metadata$prereserve_doi$doi
  
  #### end zenodo section section ####
  
  #### Send to YouTube section ####
  tuber::yt_oauth('1012121281657-tgsd76foreilsptr6oaa1ogp51ptja2f.apps.googleusercontent.com', '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')
  
  title <- presenter_data$title
  abstract <- presenter_data$abstract
  session <- presenter_data$session
  firstsur_name <- paste0(presenter_data$firstname, ' ', presenter_data$surname)
  name <- presenter_data$name
  affiliation <- presenter_data$affiliation
  ORCID <- presenter_data$ORCID
  citation <- paste0(name, ' (', substr(ESMARConfName, 10, 13), ') ', title,'. ', ESMARConfName, ' conference presentation. Zenodo. https://doi.org/', doi)
  
  #set metadata for video
  upload <- tuber::upload_video(
    file.choose(),
    snippet = list(
      title = paste0(ESMARConfName, ' ', session, ' - ', firstsur_name),
      description = paste0('Presenter: ', firstsur_name, '\nSession: ', session, '\nTitle: ', title, '\nAbstract: ', abstract, '\n\nPlease cite as: ', citation),
      keywords = c(ESMARConfName, 'EMSARConf', 'evidence synthesis', 'meta-analysis', 'RStats'),
      channelId = 'UCZy7G3R6bk6AE6Vbfgc0Qhg',
      channelTitle = "ESMARConf2022"
    ),
    status = list(
      publishAt = strftime(presenter_data$time_start, "%Y-%m-%dT%H:%M:%S%z"),
      madeForKids = FALSE,
      privacyStatus = 'private')
  )
  
  # Extract YouTube_URL
  #YouTube_URL <- upload$
  
  #### End YouTube section ####
  
  #### Add YouTube URL to Zenodo record ####
  # Update record YouTube_URL field
  myrec$addRelatedIdentifier('isIdenticalTo', YouTube_URL)
  
  # Deposit on zenodo
  myrec <- zenodo$depositRecord(myrec)
  
  # Publish on Zenodo (cannot be undone)
  #myrec <- zenodo$publishRecord(myrec$id)
  
  #### Update GoogleSheet with YouTube_URL, citation and DOI - append data to sheet 2
  # Specify access rights needed for write access to GSheets
  googlesheets4::gs4_auth()
  # Write data back to sheet
  # Identify sheet 2 to write back to
  new_data <- googlesheets4::read_sheet(abstract_url, sheet = 2)
  # Find row to edit
  rownum <- which(grepl(presenter_data$id, new_data$id)) +1 #we add 1 because headers are considered row 1 in GoogleSheets
  # Create dataframe of new data to push
  push_data <- data.frame(id = presenter_data$id, YouTube_URL, citation, doi)
  # Push data to sheet 2
  googlesheets4::sheet_append(abstract_url, push_data, sheet = 2)
  
  ### End Google Sheets update section ###
  
}
