#' Publish recording and metadata to a single record on Zenodo
#' 
#' @description 
#' @param presenter_data
#' @examples 
#' data <- import_data(data = 'abstracts')
#' abstract_data <- data$abstract_data
#' presenter_data <- abstract_data[13,]
send2zenodo <- function(presenter_data){
  
  # Lookup ESMARConf name - data sourced from inputs.csv in output folder, generated by set_values()
  dat <- read.csv(here::here("outputs", "inputs.csv"))
  ESMARConfName <- maditr::vlookup('ESMARConfName', dat, lookup_column = 'label')
  ESMARConf_startDate <- maditr::vlookup('ESMARConf_startDate', dat, lookup_column = 'label')
  ESMARConf_endDate <- maditr::vlookup('ESMARConf_endDate', dat, lookup_column = 'label')
  
  # Install development version of package from GitHub
  library(zen4R)
  # Connect to Zenodo REST API
  zenodo <- ZenodoManager$new(
    token = 'EZINvEsMsQp6wepm3HsDA1HZAN1d74Ykll8maLV22Fj2XPauG5ad15hIy0tj', 
    logger = "INFO" # use "DEBUG" to see detailed API operation logs, use NULL if you don't want logs at all
  )
  
  # Create record
  # Generate local empty record not yet deposited on Zenodo
  # Get detailed help here: ?ZenodoRecord
  myrec <- zenodo$createEmptyRecord()
  myrec$setPublicationDate(Sys.Date())
  #myrec$setEmbargoDate(as.Date(presenter_data$time_start)) - not currently working - throws the following error: 'Error in .class1(object) : object 'publicationDate' not found'
  myrec$setTitle(presenter_data$title)
  myrec$setDescription(presenter_data$abstract)
  myrec$setUploadType("presentation")
  myrec$addCreator(name = presenter_data$name, affiliation = presenter_data$affiliation, orcid = presenter_data$ORCID)
  myrec$setLanguage('eng')
  myrec$addRelatedIdentifier('isIdenticalTo', presenter_data$YouTube_URL)
  myrec$setKeywords(c(ESMARConfName,'evidence synthesis','meta-analysis','RStats'))
  myrec$setCommunities(tolower(ESMARConfName))
  myrec$setConferenceTitle(paste0('Evidence Synthesis and Meta-Analysis in R Conference ', substr(ESMARConfName, 10,13)))
  myrec$setConferenceAcronym(ESMARConfName)
  myrec$setConferenceDates(paste0(format(as.Date(ESMARConf_startDate), "%d"), ' to ', format(as.Date(ESMARConf_endDate), "%d %B %Y")))
  myrec$setConferencePlace('online')
  myrec$setConferenceUrl('https://esmarconf.github.io/')
  myrec$setConferenceSession(presenter_data$session)
  # Deposit on zenodo
  myrec <- zenodo$depositRecord(myrec)
  
  # Get record id
  myrec$id
  
  # Upload file
  # Get detailed help here: ??Zenodo
  zenodo$uploadFile('/Users/nealhaddaway/OneDrive - SEI/ESHackathon/4.Remote 2020/ESMARConf/esmarconf_updater/Untitled.mov', myrec)
  
  # Publish record (cannot be undone)
  #myrec <- zenodo$publishRecord(myrec$id)
  
}
