#' Publish recording to YouTube
#' 
#' @description 
#' @param presenter_data
#' @examples 
#' data <- import_data(data = 'abstracts')
#' abstract_data <- data$abstract_data
#' presenter_data <- abstract_data[28,]
send2youtube <- function(presenter_data){
  
  
  
  # Lookup ESMARConf name - data sourced from inputs.csv in output folder, generated by set_values()
  dat <- read.csv(here::here("outputs", "inputs.csv"))
  ESMARConfName <- maditr::vlookup('ESMARConfName', dat, lookup_column = 'label')
  ESMARConf_startDate <- maditr::vlookup('ESMARConf_startDate', dat, lookup_column = 'label')
  ESMARConf_endDate <- maditr::vlookup('ESMARConf_endDate', dat, lookup_column = 'label')
  
  # Authenticate user and channel
  #API key 1 = 'AIzaSyAtjCyjsR7mlp2ddmeNbc5h83ySEOPjn5E'
  #client id = '1012121281657-8mdpn1u1lj4pimhb37elb2njjeftjts5.apps.googleusercontent.com'
  #client secret = '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'
  
  
}
