#' Publish recording and metadata to a single record on Zenodo
#' 
#' @description 
#' @param presenter_data
#' @examples 
#' ESMARConf2022_programme <- 'https://docs.google.com/spreadsheets/d/1LF1XV6Ag-iwb5OjdG8dvRWzzOEYCqjKtHFZTajracIU/edit#gid=0'
#' data <- import_data(data = 'abstracts')
#' abstract_data <- data$abstract_data
#' session_data <- subset(abstract_data, type == 'session')
send2zenodo <- function(presenter_data){
  
  # Lookup ESMARConf name - data sourced from inputs.csv in output folder, generated by set_values()
  dat <- read.csv(here::here("outputs", "inputs.csv"))
  ESMARConfName <- maditr::vlookup('ESMARConfName', dat, lookup_column = 'label')
  ESMARConf_startDate <- maditr::vlookup('ESMARConf_startDate', dat, lookup_column = 'label')
  ESMARConf_endDate <- maditr::vlookup('ESMARConf_endDate', dat, lookup_column = 'label')
  
  # Install development version of package from GitHub
  library(zen4R)
  # Connect to Zenodo REST API
  zenodo <- ZenodoManager$new(
    token = 'EZINvEsMsQp6wepm3HsDA1HZAN1d74Ykll8maLV22Fj2XPauG5ad15hIy0tj', 
    logger = "INFO" # use "DEBUG" to see detailed API operation logs, use NULL if you don't want logs at all
  )
  
  presenter_data$abstract <- paste0('Moderator: ', presenter_data$firstname, ' ', presenter_data$surname, '\nSession: ', presenter_data$title)
  
  # loop through rows and create a Zenodo record for each row
  for (i in nrow(session_data)){
    # Create record
    # Generate local empty record not yet deposited on Zenodo
    # Get detailed help here: ?ZenodoRecord
    myrec <- zenodo$createEmptyRecord()
    myrec$setPublicationDate(Sys.Date())
    myrec$setEmbargoDate(as.Date(presenter_data$time_start[i]))
    myrec$setTitle(presenter_data$title[i])
    myrec$setDescription(presenter_data$abstract[i])
    myrec$setUploadType("presentation")
    myrec$addCreator(name = presenter_data$name[i], affiliation = presenter_data$affiliation[i], orcid = presenter_data$ORCID[i])
    myrec$setLanguage('eng')
    myrec$addRelatedIdentifier('isIdenticalTo', presenter_data$YouTube_URL[i])
    myrec$setKeywords(c(ESMARConfName,'evidence synthesis','meta-analysis','RStats'))
    myrec$setCommunities(tolower(ESMARConfName))
    myrec$setConferenceTitle(paste0('Evidence Synthesis and Meta-Analysis in R Conference ', substr(ESMARConfName, 10,13)))
    myrec$setConferenceAcronym(ESMARConfName)
    myrec$setConferenceDates(paste0(format(as.Date(ESMARConf_startDate), "%d"), ' to ', format(as.Date(ESMARConf_endDate), "%d %B %Y")))
    myrec$setConferencePlace('online')
    myrec$setConferenceUrl('https://esmarconf.github.io/')
    myrec$setConferenceSession(presenter_data$session[i])
    # Deposit on zenodo
    myrec <- zenodo$depositRecord(myrec)
  }

  
  # Upload file
  # Get detailed help here: ??Zenodo
  zenodo$uploadFile('/Users/nealhaddaway/OneDrive - SEI/ESHackathon/4.Remote 2020/ESMARConf/esmarconf_updater/Untitled.mov', myrec)
  
  # Publish record (cannot be undone)
  #myrec <- zenodo$publishRecord(myrec$id)
  
}
