---
output: html_document
---
``` {r include = FALSE}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
data <- read.csv(here::here("outputs", "inputs.csv"))
list_names <- unname(unlist(data[1]))
values <- unname(unlist(data[2]))
data <- setNames(as.list(values), list_names)
attach(data)
```
### <span style="color: #4fb4a8;">`r ESMARConfName` begins in 1 week!</span>  
<br>

Dear `r ESMARConfName` Presenter,  
<br>

`r ESMARConfName` begins in one week and we are starting to get very excited!

You should now have sent us a recording of your presentation, and it will soon be uploaded to YouTube and subtitles added and verified - many thanks for your cooperation!  

If you have not yet sent in your recording, <b>please do so immediately</b>. We need time to ensure subtitling makes our event as accessible as possible, so we really need your cooperation.  <b>Please get in contact with us urgently if you are experiencing any problems or delays</b>.  

If you are joining your session live, we look forward to seeing you there. If you provided us with a Twitter handle, questions from the audience will hopefully arrive as responses to a scheduled Tweet where you have been tagged. Your moderator will help to field questions if you have time during your session.  

If you have any questions, comments, or concerns, please let us know. We also want to remind you of our Accessibility Policy, Code of Conduct, and Complaints/concerns Procedure, available here: <a href="https://www.eshackathon.org/about/accessibility_and_codeofconduct.html">https://www.eshackathon.org/about/accessibility_and_codeofconduct.html</a>.  
<br>

Many thanks for your time and effort - see you in a week!  
The `r ESMARConfName` Organising Team